const colors = [
    "lightsalmon",
  	"salmon",
  	"darksalmon",
  	"lightcoral",
  	"indianred",
  	"crimson",
  	"firebrick", 
  	"red",
  	"darkred",
  	"tomato",
  	"orangered",
  	"gold",
  	"orange", 	
  	"darkorange",
    "coral",
    "lightyellow", 
  	"lemonchiffon",
  	"lightgoldenrodyellow ",
  	"papayawhip",
  	"moccasin",
  	"peachpuff",	
  	"palegoldenrod",
  	"khaki", 	
  	"darkkhaki",
  	"yellow",
    "lawngreen", 
  	"chartreuse",
  	"limegreen",
  	"lime",
  	"forestgreen",
  	"green",
  	"darkgreen",
  	"greenyellow", 	
  	"yellowgreen",	
  	"springgreen",	
  	"mediumspringgreen",
  	"lightgreen",
  	"palegreen",
  	"darkseagreen", 	
  	"mediumseagreen", 
  	"seagreen",
  	"olive",
  	"darkolivegreen",
  	"olivedrab",
    "lightcyan",
  	"cyan",
  	"aqua",	
  	"aquamarine",
  	"mediumaquamarine",
  	"paleturquoise",
  	"turquoise",
  	"mediumturquoise",
  	"darkturquoise",
  	"lightseagreen",
  	"cadetblue",
  	"darkcyan",
  	"teal",
    "powderblue",
  	"lightblue",	
  	"lightskyblue",
  	"skyblue",
  	"deepskyblue", 
  	"lightsteelblue",
  	"dodgerblue",
  	"cornflowerblue",
  	"steelblue",
  	"royalblue",
  	"blue",
  	"mediumblue",
  	"darkblue",
  	"navy",
  	"midnightblue",
  	"mediumslateblue",
  	"slateblue",
  	"darkslateblue",
    "lavender",
  	"thistle",
  	"plum",
  	"violet", 	
  	"orchid",	
  	"fuchsia",	
  	"magenta",	
  	"mediumorchid",
  	"mediumpurple",
  	"blueviolet",
  	"darkviolet",
  	"darkorchid",
  	"darkmagenta",
  	"purple",
  	"indigo",
    "pink",
  	"lightpink", 	
  	"vhotpink", 	
  	"deeppink", 	
  	"palevioletred",
  	"mediumvioletred",
    "white", 	
  	"snow", 	
  	"honeydew", 
  	"mintcream",
  	"azure", 	
  	"aliceblue", 
  	"ghostwhite",
  	"whitesmoke",
  	"seashell",
  	"beige",
  	"oldlace", 	
  	"floralwhite",
  	"ivory", 	
  	"antiquewhite",
  	"linen",
  	"lavenderblush",
  	"mistyrose",
    "gainsboro",
  	"lightgray",
  	"silver",
  	"darkgray", 
  	"gray", 	
  	"dimgray", 	
  	"lightslategray",
  	"slategray",
  	"darkslategray",
  	"black",
    "cornsilk",
  	"blanchedalmond",
  	"bisque",
  	"navajowhite",
  	"wheat",
  	"burlywood",
  	"tan",
  	"rosybrown",
  	"sandybrown",
  	"goldenrod",
  	"peru",
  	"chocolate",
  	"saddlebrown",
  	"sienna",
  	"brown",
  	"maroon"
];

let background = document.querySelector("body");

let button = document.querySelector(".clicker");

let colorName = document.querySelector(".color");

button.addEventListener('click', function() {
    
	let randomIndex = Math.floor(Math.random() * colors.length);
    
	let randomColor = colors[randomIndex];
    
	background.style.backgroundColor = randomColor;
    
	colorName.innerText = randomColor;
    
	if (background.style.backgroundColor === "black") {
        button.style.border = "2.5px solid white";
        button.style.color = "white";
    }

	if (background.style.backgroundColor !== "black") {
		button.style.border = "2.5px solid black";
		button.style.color = "black";
	}
});